package images

import (
	"context"
	"database/sql"
	"fmt"
	"net/http"
	"sort"
	"strings"

	"imgsearch/internal/httputil"
	"imgsearch/internal/jobkind"
	"imgsearch/internal/nsfwsql"
	"imgsearch/internal/phash"
)

const (
	// DefaultDuplicateDistance is the Hamming distance under which two dHashes
	// count as the same picture; MaxDuplicateDistance is the largest the band
	// index can answer exactly (8 bands of 8 bits find every pair within 7).
	DefaultDuplicateDistance = 4
	MaxDuplicateDistance     = 7
	duplicateBands           = 8
)

// DuplicateGroup is a set of standalone images whose hashes are within the
// requested distance of each other (transitively). Items are ordered by
// pixel count, largest first, so "keep largest" is the first entry.
type DuplicateGroup struct {
	Items []ImageItem `json:"items"`
}

// DuplicatesResponse is the body of GET /api/duplicates.
type DuplicatesResponse struct {
	Groups      []DuplicateGroup `json:"groups"`
	MaxDistance int              `json:"max_distance"`
	// Scanned counts the hashed standalone images considered.
	Scanned int `json:"scanned"`
	// Unhashed counts standalone images without a usable hash (not yet
	// scanned, or undecodable formats such as AVIF).
	Unhashed int `json:"unhashed"`
}

type hashedImage struct {
	id   int64
	hash uint64
}

// FindDuplicates groups standalone images by perceptual hash.
func FindDuplicates(ctx context.Context, db *sql.DB, modelID int64, maxDistance int, includeNSFW bool) (DuplicatesResponse, error) {
	if db == nil {
		return DuplicatesResponse{}, fmt.Errorf("images database unavailable")
	}
	if maxDistance < 0 {
		maxDistance = 0
	}
	if maxDistance > MaxDuplicateDistance {
		maxDistance = MaxDuplicateDistance
	}
	resp := DuplicatesResponse{Groups: []DuplicateGroup{}, MaxDistance: maxDistance}

	nsfwExpr := nsfwsql.TagsJSONHasNSFW("i.tags_json", "tag")
	rows, err := db.QueryContext(ctx, fmt.Sprintf(`
SELECT i.id, i.phash
FROM images i
WHERE NOT EXISTS (SELECT 1 FROM video_frames vf WHERE vf.image_id = i.id)
  AND (? = 1 OR NOT (%s))
ORDER BY i.id`, nsfwExpr), boolToInt(includeNSFW))
	if err != nil {
		return DuplicatesResponse{}, fmt.Errorf("query image hashes: %w", err)
	}
	var hashed []hashedImage
	for rows.Next() {
		var id int64
		var raw sql.NullInt64
		if err := rows.Scan(&id, &raw); err != nil {
			_ = rows.Close()
			return DuplicatesResponse{}, fmt.Errorf("scan image hash: %w", err)
		}
		if !raw.Valid || raw.Int64 == phash.Unhashable {
			resp.Unhashed++
			continue
		}
		hashed = append(hashed, hashedImage{id: id, hash: phash.FromInt64(raw.Int64)})
	}
	_ = rows.Close()
	if err := rows.Err(); err != nil {
		return DuplicatesResponse{}, err
	}
	resp.Scanned = len(hashed)

	groups := groupByHash(hashed, maxDistance)
	if len(groups) == 0 {
		return resp, nil
	}

	items, err := loadItems(ctx, db, modelID, groups)
	if err != nil {
		return DuplicatesResponse{}, err
	}
	for _, ids := range groups {
		group := DuplicateGroup{Items: make([]ImageItem, 0, len(ids))}
		for _, id := range ids {
			if item, ok := items[id]; ok {
				group.Items = append(group.Items, item)
			}
		}
		if len(group.Items) < 2 {
			continue
		}
		sort.SliceStable(group.Items, func(a, b int) bool {
			pa := group.Items[a].Width * group.Items[a].Height
			pb := group.Items[b].Width * group.Items[b].Height
			if pa != pb {
				return pa > pb
			}
			return group.Items[a].ImageID < group.Items[b].ImageID
		})
		resp.Groups = append(resp.Groups, group)
	}
	sort.SliceStable(resp.Groups, func(a, b int) bool {
		if len(resp.Groups[a].Items) != len(resp.Groups[b].Items) {
			return len(resp.Groups[a].Items) > len(resp.Groups[b].Items)
		}
		return resp.Groups[a].Items[0].ImageID < resp.Groups[b].Items[0].ImageID
	})
	return resp, nil
}

// groupByHash finds connected components of images within maxDistance.
// Candidates are generated by splitting each hash into 8 bands: two hashes
// within distance 7 must agree on at least one band (pigeonhole), so only
// band-collisions are compared and the result is exact up to that bound.
func groupByHash(hashed []hashedImage, maxDistance int) [][]int64 {
	parent := make([]int, len(hashed))
	for i := range parent {
		parent[i] = i
	}
	var find func(int) int
	find = func(i int) int {
		for parent[i] != i {
			parent[i] = parent[parent[i]]
			i = parent[i]
		}
		return i
	}
	union := func(a, b int) {
		ra, rb := find(a), find(b)
		if ra != rb {
			parent[rb] = ra
		}
	}

	buckets := make(map[uint32][]int)
	for band := 0; band < duplicateBands; band++ {
		for k := range buckets {
			delete(buckets, k)
		}
		shift := uint(band * 8)
		for i, h := range hashed {
			key := uint32(band)<<8 | uint32((h.hash>>shift)&0xff)
			buckets[key] = append(buckets[key], i)
		}
		for _, members := range buckets {
			if len(members) < 2 {
				continue
			}
			for a := 0; a < len(members); a++ {
				for b := a + 1; b < len(members); b++ {
					ia, ib := members[a], members[b]
					if find(ia) == find(ib) {
						continue
					}
					if phash.Distance(hashed[ia].hash, hashed[ib].hash) <= maxDistance {
						union(ia, ib)
					}
				}
			}
		}
	}

	byRoot := make(map[int][]int64)
	for i := range hashed {
		root := find(i)
		byRoot[root] = append(byRoot[root], hashed[i].id)
	}
	var groups [][]int64
	for _, ids := range byRoot {
		if len(ids) >= 2 {
			groups = append(groups, ids)
		}
	}
	sort.Slice(groups, func(a, b int) bool { return groups[a][0] < groups[b][0] })
	return groups
}

func loadItems(ctx context.Context, db *sql.DB, modelID int64, groups [][]int64) (map[int64]ImageItem, error) {
	items := make(map[int64]ImageItem)
	var ids []int64
	for _, group := range groups {
		ids = append(ids, group...)
	}
	const chunk = 400
	for start := 0; start < len(ids); start += chunk {
		end := start + chunk
		if end > len(ids) {
			end = len(ids)
		}
		part := ids[start:end]
		args := []any{modelID, jobkind.EmbedImage}
		placeholders := make([]string, len(part))
		for i, id := range part {
			placeholders[i] = "?"
			args = append(args, id)
		}
		rows, err := db.QueryContext(ctx, imageItemSelect+`
WHERE i.id IN (`+strings.Join(placeholders, ",")+`)`, args...)
		if err != nil {
			return nil, fmt.Errorf("query duplicate items: %w", err)
		}
		for rows.Next() {
			item, err := scanImageItem(rows)
			if err != nil {
				_ = rows.Close()
				return nil, err
			}
			items[item.ImageID] = item
		}
		_ = rows.Close()
		if err := rows.Err(); err != nil {
			return nil, err
		}
	}
	return items, nil
}

// NewDuplicatesHandler serves GET /api/duplicates?distance=N&include_nsfw=1.
func NewDuplicatesHandler(h *Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			httputil.WriteMethodNotAllowed(w, http.MethodGet)
			return
		}
		if h == nil || h.DB == nil {
			httputil.WriteJSONError(w, http.StatusServiceUnavailable, "service unavailable")
			return
		}
		distance := int(httputil.ParseInt64Query(r, "distance", DefaultDuplicateDistance))
		resp, err := FindDuplicates(r.Context(), h.DB, h.ModelID, distance, httputil.ParseIncludeNSFWQuery(r))
		if err != nil {
			httputil.WriteJSONError(w, http.StatusInternalServerError, "query failed")
			return
		}
		httputil.WriteJSON(w, http.StatusOK, resp)
	})
}
